repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
    - id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.0
    hooks:
    - id: ruff
-   repo: local
    hooks:
    - id: block-private-keys
      name: Block private SSH/PEM keys
      entry: bash scripts/prevent-commit-key-check.sh
      language: script
      files: ''
